version: "3.7"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: frontend
    ports:
      - 8081:8080
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./spring_api
      dockerfile: ./Dockerfile
    container_name: backend
    ports:
      - 8080:8080

  postgres_db:
    image: postgres:14
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
volumes:
  db-store: