server:
  servlet:
    context-path: /spring_api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/db
    password: root
    username: hoge
  jpa:
    database: POSTGRESQL
